// USING THE CONTEXT API FOR SMALL APPLICATION
//  FOR LONG USE REDUX FOR STATE MANEGMENT PUPOSE 
// AND ALSO FOR TRADITIONAL PUPOSE USE NORMAL CHANING
//  STATE MANEEGMENT PURPOSE.
// #CONTEXT API IS NOT A HOOK IS IS A METHOD


// IMPORT THE CONTEXT API

import { createContext } from 'react';


// EXPORT THE CONTEX API

export const CartContext = createContext(null);

